structure(list(method = "GET", url = "https://dashboard-api.labs.transitmatters.org/api/linedelays?start_date=2024-01-01&end_date=2024-01-31&line=Red", 
    status_code = 200L, headers = structure(list(date = "Wed, 24 Jun 2026 15:23:06 GMT", 
        `content-type` = "application/json", `content-length` = "339", 
        `x-amzn-requestid` = "09f3099e-9987-4e4d-8cb9-ad75ae775c11", 
        `access-control-allow-origin` = "https://dashboard.transitmatters.org", 
        `content-encoding` = "deflate", `access-control-allow-headers` = "Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key", 
        `x-amz-apigw-id` = "feNuOFw5IAMECig=", `cache-control` = "public, max-age=7776000", 
        `x-amzn-trace-id` = "Root=1-6a3bf65a-28074a8d7fc10cc20d6c8244;Parent=2e5b842899e5a60f;Sampled=0;Lineage=1:1e0fd665:0", 
        `access-control-max-age` = "3600"), class = "httr2_headers"), 
    body = charToRaw("[\n    {\n        \"brake_problem\": 0,\n        \"car_traffic\": 0,\n        \"date\": \"2024-01-01\",\n        \"disabled_vehicle\": 20,\n        \"door_problem\": 0,\n        \"fire\": 0,\n        \"flooding\": 0,\n        \"line\": \"Red\",\n        \"mechanical_problem\": 0,\n        \"medical_emergency\": 0,\n        \"other\": 100,\n        \"police_activity\": 0,\n        \"power_problem\": 0,\n        \"signal_problem\": 0,\n        \"switch_problem\": 0,\n        \"total_delay_time\": 120,\n        \"track_issue\": 0,\n        \"track_work\": 0\n    },\n    {\n        \"brake_problem\": 0,\n        \"car_traffic\": 0,\n        \"date\": \"2024-01-08\",\n        \"disabled_vehicle\": 65,\n        \"door_problem\": 45,\n        \"fire\": 0,\n        \"flooding\": 160,\n        \"line\": \"Red\",\n        \"mechanical_problem\": 0,\n        \"medical_emergency\": 0,\n        \"other\": 0,\n        \"police_activity\": 0,\n        \"power_problem\": 0,\n        \"signal_problem\": 0,\n        \"switch_problem\": 0,\n        \"total_delay_time\": 270,\n        \"track_issue\": 0,\n        \"track_work\": 0\n    },\n    {\n        \"brake_problem\": 0,\n        \"car_traffic\": 0,\n        \"date\": \"2024-01-15\",\n        \"disabled_vehicle\": 80,\n        \"door_problem\": 0,\n        \"fire\": 0,\n        \"flooding\": 0,\n        \"line\": \"Red\",\n        \"mechanical_problem\": 20,\n        \"medical_emergency\": 0,\n        \"other\": 95,\n        \"police_activity\": 75,\n        \"power_problem\": 0,\n        \"signal_problem\": 60,\n        \"switch_problem\": 0,\n        \"total_delay_time\": 365,\n        \"track_issue\": 20,\n        \"track_work\": 15\n    },\n    {\n        \"brake_problem\": 0,\n        \"car_traffic\": 0,\n        \"date\": \"2024-01-22\",\n        \"disabled_vehicle\": 75,\n        \"door_problem\": 0,\n        \"fire\": 0,\n        \"flooding\": 0,\n        \"line\": \"Red\",\n        \"mechanical_problem\": 0,\n        \"medical_emergency\": 115,\n        \"other\": 20,\n        \"police_activity\": 30,\n        \"power_problem\": 0,\n        \"signal_problem\": 15,\n        \"switch_problem\": 0,\n        \"total_delay_time\": 255,\n        \"track_issue\": 0,\n        \"track_work\": 0\n    },\n    {\n        \"brake_problem\": 0,\n        \"car_traffic\": 0,\n        \"date\": \"2024-01-29\",\n        \"disabled_vehicle\": 170,\n        \"door_problem\": 40,\n        \"fire\": 0,\n        \"flooding\": 0,\n        \"line\": \"Red\",\n        \"mechanical_problem\": 0,\n        \"medical_emergency\": 45,\n        \"other\": 10,\n        \"police_activity\": 10,\n        \"power_problem\": 0,\n        \"signal_problem\": 15,\n        \"switch_problem\": 0,\n        \"total_delay_time\": 290,\n        \"track_issue\": 0,\n        \"track_work\": 0\n    }\n]"), 
    timing = c(redirect = 0, namelookup = 1.2e-05, connect = 0, 
    pretransfer = 5.9e-05, starttransfer = 0.052592, total = 0.052642
    ), cache = new.env(parent = emptyenv())), class = "httr2_response")
